# Generated by Django 5.2.5 on 2026-03-14 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='penalty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contest.contest'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error')], max_length=10),
        ),
    ]
