# Generated by Django 5.2.5 on 2026-03-17 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_leaderboard_penalty_leaderboard_solved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='points',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='ContestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('solved_count', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'contest')},
            },
        ),
        migrations.CreateModel(
            name='ProblemSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.TextField(blank=True)),
                ('language_id', models.IntegerField(default=71)),
                ('score', models.IntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('passed_testcases', models.IntegerField(default=0)),
                ('total_testcases', models.IntegerField(default=0)),
                ('contest_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_submissions', to='contest.contestsubmission')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.problem')),
            ],
        ),
    ]
