# Generated by Django 5.2.5 on 2026-03-22 16:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_remove_leaderboard_penalty_leaderboard_submitted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contestsubmission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='contestsubmission',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='contestsubmission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='problemsubmission',
            name='contest_submission',
        ),
        migrations.RemoveField(
            model_name='problemsubmission',
            name='problem',
        ),
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterModelOptions(
            name='contestproblem',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ['rank', '-score', 'penalty', 'last_updated']},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='leaderboard',
            old_name='submitted_at',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.AddField(
            model_name='contest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='penalty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testcase',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='contest.contest'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='solved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problem',
            name='constraints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='points',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error'), ('PENDING', 'Pending')], default='PENDING', max_length=10),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['contest'], name='contest_sub_contest_01fc91_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['problem'], name='contest_sub_problem_add2fa_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user'], name='contest_sub_user_id_dc5f51_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='contest_sub_status_cb7729_idx'),
        ),
        migrations.DeleteModel(
            name='ContestSubmission',
        ),
        migrations.DeleteModel(
            name='ProblemSubmission',
        ),
    ]
