# Generated by Django 5.2 on 2026-03-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_contestregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='is_hidden',
            field=models.BooleanField(default=True),
        ),
    ]
