# Generated by Django 5.2 on 2026-05-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_testcase_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
