# Generated by Django 5.2 on 2026-05-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_testcase_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='scheduled_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
